const LOGIN_PENDING = 'LOGIN_PENDING';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';

const REGISTER_PENDING = 'REGISTER_PENDING';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const loginTypes = {
	LOGIN_PENDING,
	LOGIN_SUCCESS,
	LOGIN_FAILED
}

export const registerType = {
	REGISTER_PENDING,
	REGISTER_SUCCESS,
	REGISTER_FAILURE
}